---
# Load credentials from vault vars, or generate them if not set.
# Generated credentials are written to vault.yml at the end of a deploy.

- name: Generate database_password if not set
  ansible.builtin.set_fact:
    database_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: not database_password
  run_once: true
  delegate_to: localhost

- name: Generate user_password if not set
  ansible.builtin.set_fact:
    user_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: not user_password
  run_once: true
  delegate_to: localhost

- name: Generate admin_password if not set
  ansible.builtin.set_fact:
    admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: not admin_password
  run_once: true
  delegate_to: localhost

- name: Generate manager_token if not set
  ansible.builtin.set_fact:
    manager_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: not manager_token
  run_once: true
  delegate_to: localhost

- name: Generate registration_token if not set
  ansible.builtin.set_fact:
    registration_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=22') }}"
  when: not registration_token
  run_once: true
  delegate_to: localhost
